import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const now = new Date();
    const sampleProducts = [
        // Electronics (15 items)
        {
            name: 'ProBook X1 Carbon Gen 11',
            category: 'electronics',
            price: 1899.99,
            stock: 25,
            status: 'active',
            rating: 4.7,
            image: 'https://placehold.co/600x400/FF0000/FFFFFF/png?text=ProBook+X1',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 30).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 29).toISOString(),
        },
        {
            name: 'Galaxy S24 Ultra 5G',
            category: 'electronics',
            price: 1199.99,
            stock: 40,
            status: 'active',
            rating: 4.8,
            image: 'https://placehold.co/600x400/0000FF/FFFFFF/png?text=Galaxy+S24',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 28).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 27).toISOString(),
        },
        {
            name: 'iPad Pro M4 (13-inch)',
            category: 'electronics',
            price: 1499.00,
            stock: 30,
            status: 'active',
            rating: 4.9,
            image: 'https://placehold.co/600x400/FFFF00/000000/png?text=iPad+Pro',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 25).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 24).toISOString(),
        },
        {
            name: 'Sony WH-1000XM5 Noise Cancelling Headphones',
            category: 'electronics',
            price: 348.00,
            stock: 50,
            status: 'active',
            rating: 4.6,
            image: 'https://placehold.co/600x400/00FFFF/000000/png?text=Sony+Headphones',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 22).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 21).toISOString(),
        },
        {
            name: 'Canon EOS R5 Mirrorless Camera',
            category: 'electronics',
            price: 2899.00,
            stock: 10,
            status: 'active',
            rating: 4.9,
            image: 'https://placehold.co/600x400/FF00FF/000000/png?text=Canon+R5',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 20).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 19).toISOString(),
        },
        {
            name: 'Apple Watch Series 9',
            category: 'electronics',
            price: 399.00,
            stock: 35,
            status: 'active',
            rating: 4.5,
            image: 'https://placehold.co/600x400/800000/FFFFFF/png?text=Apple+Watch',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 18).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 17).toISOString(),
        },
        {
            name: 'Nintendo Switch OLED Model',
            category: 'electronics',
            price: 349.99,
            stock: 45,
            status: 'active',
            rating: 4.7,
            image: 'https://placehold.co/600x400/008000/FFFFFF/png?text=Nintendo+Switch',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 15).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 14).toISOString(),
        },
        {
            name: 'Dell XPS 15 Laptop',
            category: 'electronics',
            price: 1799.00,
            stock: 20,
            status: 'active',
            rating: 4.6,
            image: 'https://placehold.co/600x400/000080/FFFFFF/png?text=Dell+XPS',

            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 12).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 11).toISOString(),
        },
        {
            name: 'Google Pixel 8 Pro',
            category: 'electronics',
            price: 899.00,
            stock: 38,
            status: 'active',
            rating: 4.5,
            image: 'https://placehold.co/600x400/808000/FFFFFF/png?text=Pixel+8+Pro',

            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 10).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 9).toISOString(),
        },
        {
            name: 'Samsung Galaxy Tab S9+',
            category: 'electronics',
            price: 999.00,
            stock: 28,
            status: 'active',
            rating: 4.7,
            image: 'https://placehold.co/600x400/800080/FFFFFF/png?text=Galaxy+Tab',

            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 8).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 7).toISOString(),
        },
        {
            name: 'Bose QuietComfort Earbuds II',
            category: 'electronics',
            price: 279.00,
            stock: 42,
            status: 'active',
            rating: 4.4,
            image: 'https://placehold.co/600x400/008080/FFFFFF/png?text=Bose+Earbuds',

            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 6).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 5).toISOString(),
        },
        {
            name: 'GoPro HERO12 Black',
            category: 'electronics',
            price: 399.99,
            stock: 15,
            status: 'active',
            rating: 4.6,
            image: 'https://placehold.co/600x400/C0C0C0/000000/png?text=GoPro+HERO12',

            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 4).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 3).toISOString(),
        },
        {
            name: 'Fitbit Charge 6 Fitness Tracker',
            category: 'electronics',
            price: 159.95,
            stock: 50,
            status: 'active',
            rating: 4.2,
            image: 'https://placehold.co/600x400/A0A0A0/FFFFFF/png?text=Fitbit+Charge+6',

            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 2).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1).toISOString(),
        },
        {
            name: 'PlayStation 5 Slim Console',
            category: 'electronics',
            price: 499.99,
            stock: 22,
            status: 'active',
            rating: 4.8,
            image: 'https://placehold.co/600x400/606060/FFFFFF/png?text=PS5+Slim',

            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString(),
        },
        {
            name: 'HP Spectre x360 Convertible Laptop',
            category: 'electronics',
            price: 1599.00,
            stock: 18,
            status: 'inactive', // Inactive product
            rating: 3.5,
            image: 'https://placehold.co/600x400/404040/FFFFFF/png?text=HPSpectre',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 60).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 50).toISOString(),
        },

        // Books (15 items)
        {
            name: 'The Midnight Library',
            category: 'books',
            price: 14.99,
            stock: 80,
            status: 'active',
            rating: 4.5,
            image: 'https://placehold.co/600x400/8B4513/FFFFFF/png?text=The+Midnight+Library',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 40).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 39).toISOString(),
        },
        {
            name: 'Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones',
            category: 'books',
            price: 22.99,
            stock: 95,
            status: 'active',
            rating: 4.9,
            image: 'https://placehold.co/600x400/A0522D/FFFFFF/png?text=Atomic+Habits',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 38).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 37).toISOString(),
        },
        {
            name: 'Clean Code: A Handbook of Agile Software Craftsmanship',
            category: 'books',
            price: 49.99,
            stock: 60,
            status: 'active',
            rating: 4.7,
            image: 'https://placehold.co/600x400/D2B48C/000000/png?text=Clean+Code',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 35).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 34).toISOString(),
        },
        {
            name: 'The Psychology of Money: Timeless lessons on wealth, greed, and happiness',
            category: 'books',
            price: 18.50,
            stock: 70,
            status: 'active',
            rating: 4.8,
            image: 'https://placehold.co/600x400/F4A460/000000/png?text=Psychology+Money',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 32).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 31).toISOString(),
        },
        {
            name: 'Educated: A Memoir',
            category: 'books',
            price: 16.00,
            stock: 55,
            status: 'active',
            rating: 4.6,
            image: 'https://placehold.co/600x400/CD853F/000000/png?text=Educated+Memoir',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 29).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 28).toISOString(),
        },
        {
            name: 'Project Hail Mary',
            category: 'books',
            price: 15.99,
            stock: 90,
            status: 'active',
            rating: 4.8,
            image: 'https://placehold.co/600x400/8B4513/FFFFFF/png?text=Project+Hail+Mary',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 26).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 25).toISOString(),
        },
        {
            name: 'The Pragmatic Programmer: Your Journey To Mastery',
            category: 'books',
            price: 59.99,
            stock: 45,
            status: 'active',
            rating: 4.7,
            image: 'https://placehold.co/600x400/A0522D/FFFFFF/png?text=Pragmatic+Programmer',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 23).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 22).toISOString(),
        },
        {
            name: 'Dune (Barnes & Noble Collectible Editions)',
            category: 'books',
            price: 29.99,
            stock: 30,
            status: 'active',
            rating: 4.9,
            image: "https://placehold.co/600x400/D2B48C/000000/png?text=Dune+Collectible",
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 20).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 19).toISOString(),
        },
        {
            name: 'Sapiens: A Brief History of Humankind',
            category: 'books',
            price: 19.99,
            stock: 75,
            status: 'active',
            rating: 4.6,
            image: 'https://placehold.co/600x400/F4A460/000000/png?text=Sapiens',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 17).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 16).toISOString(),
        },
        {
            name: 'Never Split the Difference: Negotiating As If Your Life Depended On It',
            category: 'books',
            price: 17.50,
            stock: 65,
            status: 'active',
            rating: 4.8,
            image: 'https://placehold.co/600x400/CD853F/000000/png?text=Never+Split',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 14).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 13).toISOString(),
        },
        {
            name: 'The Lord of the Rings 3-Book Paperback Box Set',
            category: 'books',
            price: 25.00,
            stock: 50,
            status: 'active',
            rating: 4.9,
            image: 'https://placehold.co/600x400/8B4513/FFFFFF/png?text=LOTR+Box+Set',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 11).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 10).toISOString(),
        },
        {
            name: 'Start With Why: How Great Leaders Inspire Everyone to Take Action',
            category: 'books',
            price: 16.99,
            stock: 88,
            status: 'active',
            rating: 4.7,
            image: 'https://placehold.co/600x400/A0522D/FFFFFF/png?text=Start+With+Why',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 8).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 7).toISOString(),
        },
        {
            name: 'JavaScript: The Good Parts',
            category: 'books',
            price: 32.99,
            stock: 40,
            status: 'active',
            rating: 4.2,
            image: 'https://placehold.co/600x400/D2B48C/000000/png?text=JavaScript+Good+Parts',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 5).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 4).toISOString(),
        },
        {
            name: 'Becoming',
            category: 'books',
            price: 14.00,
            stock: 60,
            status: 'active',
            rating: 4.6,
            image: 'https://placehold.co/600x400/F4A460/000000/png?text=Becoming+Memoir',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 2).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1).toISOString(),
        },
        {
            name: 'The Alchemist',
            category: 'books',
            price: 11.99,
            stock: 12,
            status: 'inactive', // Inactive product
            rating: 3.8,
            image: 'https://placehold.co/600x400/CD853F/000000/png?text=The+Alchemist',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 90).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 80).toISOString(),
        },

        // Clothing (15 items)
        {
            name: "Men's Classic Fit T-Shirt",
            category: 'clothing',
            price: 24.99,
            stock: 75,
            status: 'active',
            rating: 4.2,
            image: 'https://placehold.co/600x400/ADD8E6/000000/png?text=Mens+Tees',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 25).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 24).toISOString(),
        },
        {
            name: "Women's High-Waist Skinny Jeans",
            category: 'clothing',
            price: 59.99,
            stock: 60,
            status: 'active',
            rating: 4.5,
            image: 'https://placehold.co/600x400/B0E0E6/000000/png?text=Womens+Jeans',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 23).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 22).toISOString(),
        },
        {
            name: "Unisex Padded Winter Jacket",
            category: 'clothing',
            price: 129.99,
            stock: 30,
            status: 'active',
            rating: 4.7,
            image: 'https://placehold.co/600x400/ADD8E6/000000/png?text=Winter+Jacket',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 20).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 19).toISOString(),
        },
        {
            name: "Men's Running Shoes (Size 10)",
            category: 'clothing',
            price: 89.99,
            stock: 20,
            status: 'active',
            rating: 4.6,
            image: 'https://placehold.co/600x400/B0E0E6/000000/png?text=Running+Shoes',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 18).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 17).toISOString(),
        },
        {
            name: "Leather Crossbody Bag (Black)",
            category: 'clothing',
            price: 79.99,
            stock: 40,
            status: 'active',
            rating: 4.3,
            image: 'https://placehold.co/600x400/ADD8E6/000000/png?text=Crossbody+Bag',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 15).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 14).toISOString(),
        },
        {
            name: "Women's Summer Dress",
            category: 'clothing',
            price: 45.00,
            stock: 55,
            status: 'active',
            rating: 4.0,
            image: 'https://placehold.co/600x400/B0E0E6/000000/png?text=Summer+Dress',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 13).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 12).toISOString(),
        },
        {
            name: "Men's Slim Fit Chinos",
            category: 'clothing',
            price: 49.99,
            stock: 0, // Out of stock
            status: 'active',
            rating: 4.1,
            image: 'https://placehold.co/600x400/ADD8E6/000000/png?text=Mens+Chinos',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 10).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 9).toISOString(),
        },
        {
            name: "Unisex Crew Neck Sweatshirt",
            category: 'clothing',
            price: 38.00,
            stock: 65,
            status: 'active',
            rating: 4.4,
            image: 'https://placehold.co/600x400/B0E0E6/000000/png?text=Crewneck+Sweatshirt',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 8).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 7).toISOString(),
        },
        {
            name: "Classic Denim Jacket",
            category: 'clothing',
            price: 75.00,
            stock: 25,
            status: 'active',
            rating: 4.5,
            image: 'https://placehold.co/600x400/ADD8E6/000000/png?text=Denim+Jacket',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 6).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 5).toISOString(),
        },
        {
            name: "Women's Slip-On Sneakers",
            category: 'clothing',
            price: 65.00,
            stock: 35,
            status: 'active',
            rating: 4.3,
            image: 'https://placehold.co/600x400/B0E0E6/000000/png?text=Slip-On+Sneakers',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 4).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 3).toISOString(),
        },
        {
            name: "Vintage Sunglasses",
            category: 'clothing',
            price: 29.99,
            stock: 50,
            status: 'active',
            rating: 3.9,
            image: 'https://placehold.co/600x400/ADD8E6/000000/png?text=Sunglasses',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 2).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1).toISOString(),
        },
        {
            name: "Men's Formal Dress Shirt",
            category: 'clothing',
            price: 39.99,
            stock: 45,
            status: 'active',
            rating: 4.2,
            image: 'https://placehold.co/600x400/B0E0E6/000000/png?text=Formal+Shirt',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString(),
        },
        {
            name: "Women's Yoga Pants",
            category: 'clothing',
            price: 35.00,
            stock: 70,
            status: 'active',
            rating: 4.6,
            image: 'https://placehold.co/600x400/ADD8E6/000000/png?text=Yoga+Pants',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString(),
        },
        {
            name: "Baseball Cap with Logo",
            category: 'clothing',
            price: 19.99,
            stock: 60,
            status: 'active',
            rating: 3.8,
            image: 'https://placehold.co/600x400/B0E0E6/000000/png?text=Baseball+Cap',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString(),
        },
        {
            name: "Classic Trench Coat",
            category: 'clothing',
            price: 199.99,
            stock: 5,
            status: 'discontinued', // Discontinued product
            rating: 3.2,
            image: 'https://placehold.co/600x400/ADD8E6/000000/png?text=Trench+Coat',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 120).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 100).toISOString(),
        },

        // Home (10 items)
        {
            name: 'Mid-Century Modern Sofa',
            category: 'home',
            price: 799.99,
            stock: 8,
            status: 'active',
            rating: 4.5,
            image: 'https://placehold.co/600x400/D3D3D3/000000/png?text=Modern+Sofa',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 30).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 29).toISOString(),
        },
        {
            name: 'Abstract Canvas Wall Art',
            category: 'home',
            price: 89.99,
            stock: 25,
            status: 'active',
            rating: 4.1,
            image: 'https://placehold.co/600x400/E0E0E0/000000/png?text=Wall+Art',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 28).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 27).toISOString(),
        },
        {
            name: 'Stainless Steel Coffee Maker',
            category: 'home',
            price: 129.99,
            stock: 15,
            status: 'active',
            rating: 4.6,
            image: 'https://placehold.co/600x400/D3D3D3/000000/png?text=Coffee+Maker',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 25).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 24).toISOString(),
        },
        {
            name: 'Ergonomic Garden Kneeler',
            category: 'home',
            price: 34.99,
            stock: 30,
            status: 'active',
            rating: 4.2,
            image: 'https://placehold.co/600x400/E0E0E0/000000/png?text=Garden+Kneeler',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 22).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 21).toISOString(),
        },
        {
            name: 'Memory Foam Mattress Topper (Queen)',
            category: 'home',
            price: 199.00,
            stock: 12,
            status: 'active',
            rating: 4.7,
            image: 'https://placehold.co/600x400/D3D3D3/000000/png?text=Mattress+Topper',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 20).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 19).toISOString(),
        },
        {
            name: 'Smart WiFi Plug (4-pack)',
            category: 'home',
            price: 49.99,
            stock: 20,
            status: 'active',
            rating: 4.3,
            image: 'https://placehold.co/600x400/E0E0E0/000000/png?text=Smart+Plug',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 18).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 17).toISOString(),
        },
        {
            name: 'Ceramic Dinnerware Set (4 settings)',
            category: 'home',
            price: 69.99,
            stock: 18,
            status: 'active',
            rating: 4.4,
            image: 'https://placehold.co/600x400/D3D3D3/000000/png?text=Dinnerware+Set',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 15).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 14).toISOString(),
        },
        {
            name: 'Robot Vacuum Cleaner',
            category: 'home',
            price: 299.00,
            stock: 10,
            status: 'active',
            rating: 4.6,
            image: 'https://placehold.co/600x400/E0E0E0/000000/png?text=Robot+Vacuum',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 12).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 11).toISOString(),
        },
        {
            name: 'Potted Indoor Palm Plant',
            category: 'home',
            price: 55.00,
            stock: 28,
            status: 'active',
            rating: 4.0,
            image: 'https://placehold.co/600x400/D3D3D3/000000/png?text=Indoor+Plant',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 10).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 9).toISOString(),
        },
        {
            name: 'Premium BBQ Grill Set',
            category: 'home',
            price: 79.00,
            stock: 2,
            status: 'discontinued', // Discontinued
            rating: 3.0,
            image: 'https://placehold.co/600x400/E0E0E0/000000/png?text=BBQ+Grill+Set',
            createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 70).toISOString(),
            updatedAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 60).toISOString(),
        },

    ];

    await db.insert(products).values(sampleProducts);

    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});